export const ACTIONS = {
  ADD_TO_BASKET: "ADD_TO_BASKET",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
  REMOVE_ALL_ITEMS_WITH_SAME_ID_FROM_BASKET: "REMOVE_ALL_ITEMS_WITH_SAME_ID_FROM_BASKET",
  SET_USER: "SET_USER",
  CLEAR_BASKET: "CLEAR_BASKET",
  CHANGE_MODAL_STATE: "CHANGE_MODAL_STATE",
  ADD_OR_MODIFY_ADDRESS: "ADD_OR_MODIFY_ADDRESS",
  REMOVE_ADDRESS: "REMOVE_ADDRESS",
  ADD_TO_ORDER_HISTORY: "ADD_TO_ORDER_HISTORY",
};
